### PR TITLE
Consolidate GTK app Code.as / GitHub repos

### PR DESCRIPTION
**Pull request by BrainBlasted**
This PR takes care of the work needed to bring the Code.as and GitHub codebases into one space. The main changes:

* The dependencies are no longer bundled, using only submodules
* The app ID is set dynamically with meson

### CODE REVIEW

**Comment by BrainBlasted** [comment]
I "fixed" it, but that involved reverting the changes around `gb`. We'll have to see if I can get `gb` to work for the flatpak build, then.

**Comment by thebaer** [comment]
Alright, sounds good. We should be set for the scope of this task, at least.

Do we need to update the build instructions in the README, too? With a clean repo, when I run `meson build` now I get this output / error:

```
The Meson build system
Version: 0.51.1
Source dir: /home/mattbaer/projects/gtk/writeas-gtk
Build dir: /home/mattbaer/projects/gtk/writeas-gtk/build
Build type: native build
Project name: writeas-gtk
Project version: 1.0.2
C compiler for the build machine: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Vala compiler for the build machine: valac (valac 0.40.11)
C compiler for the host machine: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Vala compiler for the host machine: valac (valac 0.40.11)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring config.h using configuration
Configuring writeas-gtk.desktop using configuration
Configuring writeas-gtk.appdata.xml using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gtk+-3.0 found: YES 3.22.30
Run-time dependency gtksourceview-3.0 found: YES 3.24.7

meson.build:24:0: ERROR: Non-existent build file 'fonts/lora/meson.build'
```

**Comment by BrainBlasted** [comment]
You need to do a recursive clone or initialize the submodules after cloning.

**Comment by BrainBlasted** [comment]
Note: that aspect isn't different from the current master branch. So the directions could use an update, but that's unrelated to this PR.

**Comment by thebaer** [comment]
Thanks, I'd forgotten about that. Everything builds just fine :+1: 

There's just one last difference between the normal Code.as build and the GitHub / elementary version: the Code.as build didn't include the changes in #14.

If it's possible, and if there's no compelling reason _not_ to do this, I'd like to keep the small icons in the `writeas-gtk` build and the large icons in the `com.github.writeas.writeas-gtk` build. What do you think?

**Comment by BrainBlasted** [comment]
Done. I think this should be good to go once this pipeline finishes.

**Comment by thebaer** [comment]
Awesome, looks great! Merging now.

**Pull request merged**
