### PR TITLE
Fix black bar

### LINKED ISSUE #19: Black bar appears on the left when scrollbar is visible
After writing for a bit, sometimes I get this:

screenshot from 2018-12-19 10 04 19

I haven't yet figured out what's causing it.

### PR DESCRIPTION
**Pull request by cassidyjames**
This assigns the same `padding` values to the underlying TextView's built-in [`left_margin`](https://valadoc.org/gtk+-3.0/Gtk.TextView.left_margin.html) and [`right_margin`](https://valadoc.org/gtk+-3.0/Gtk.TextView.right_margin.html) properties instead of setting it in CSS. This fixes #19 in the elementary stylesheet.

### CODE REVIEW

**Comment by thebaer** [comment]
Perfect, thanks for this fix!

**Comment by thebaer** [comment]
By the way, do you know why this was happening? Is there something in particular to watch out for when setting padding on elements like this?

**Comment by cassidyjames** [comment]
@thebaer I'm not sure, honestly. I've not seen that specific issue before, but have seen weird black areas when using opacity/transparency in CSS. It really depends on the stylesheet being used (i.e. elementary vs Ubuntu/Ambiance), too.

**Comment by cassidyjames** [comment]
Generally if something is possible to do using widget properties instead of CSS I'll err on the side of doing that, as it seems better optimized, too.

**Comment by thebaer** [comment]
Gotcha, definitely makes sense. Will keep that in mind for the future

**Pull request merged**
